### ISSUE TITLE
How instal this card with the sensor 

### ISSUE THREAD

**Issue by Frankymuc** [silviokennecke/ha-public-transport-connection-card#2]
hi, i have install the Deutsche Bahn Homeassistant Sensor. A link to your site is for the card.
i have all test copy in HA config  / wwww and more, but the card is not visible..
the code i have as raw includet and much more.im confused becuae no readme is found how this card must integredet..

can you write how must i do ..im not a profi , im beginner with HA

**Comment by silviokennecke** [comment]
Hi @Frankymuc , I’ll get back to you this evening

**Comment by silviokennecke** [comment]
Sorry for missing to answer, but great you found the issue yourself
